services:
    gpc.rename_user.controller:
        class: gpc\rename_user\controller\main
        arguments:
            - '@config'
            - '@controller.helper'
            - '@template'
            - '@user'
            - '@auth'
            - '@request'
            - '@dbal.conn'
            - '%core.php_ext%'
            - '%core.root_path%'
            - '%core.table_prefix%'
            - '@pagination'
            - '@cache'

